name: CI/CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install + Build + Test
    container: node:16.20-alpine
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn build
      - run: yarn test
