name: CI
on:
  push:
    branches:
      - "*"
jobs:
  build:
    name: Install + Test + Build
    runs-on: ubuntu-latest
    container: node:16.13-alpine
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn test
      - run: yarn build
